CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20),
    birth_date DATE,
    email VARCHAR(40),
    login VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MPA (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS film (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100),
    description varchar(255),
    release_date date,
    duration integer,
    mpa_id integer REFERENCES MPA (mpa_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friend (
    user_id INTEGER REFERENCES USERS (user_id),
    is_approved BIT,
    user2_id INTEGER REFERENCES USERS (user_id)
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS genre_film (
    genre_id INTEGER REFERENCES genre (genre_id),
    film_id INTEGER REFERENCES film (film_id)
);

CREATE TABLE IF NOT EXISTS likes_film(
    film_id INTEGER REFERENCES film(film_id),
    user_id INTEGER REFERENCES users(user_id)
);

